# .github/workflows/deploy-frontend.yml
name: Deploy to Frontend EC2

on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload setup‐frontend.sh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "setup-frontend.sh"          # only the one script
          target: "~/"
          timeout: "1200s"  

      - name: Run setup on Frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x ~/setup-frontend.sh
            sudo ~/setup-frontend.sh
