name: Deploy to Frontend EC2

on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Render setup-frontend.sh from template
        run: |
          export frontend_repo_url="https://github.com/juani8/marketplace.git"
          export vite_backend_url="${{ secrets.VITE_BACKEND_URL }}"
          export try_files_directiva='\$uri \$uri/ /index.html'
          envsubst '${frontend_repo_url} ${vite_backend_url} ${try_files_directiva}' \
            < setup-frontend.sh.tpl > setup-frontend.sh

      - name: (Debug) Show rendered setup-frontend.sh
        run: cat setup-frontend.sh

      - name: Upload setup-frontend.sh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "setup-frontend.sh"
          target: "~/"
          timeout: "1200s"

      - name: Run setup on Frontend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x ~/setup-frontend.sh
            sudo ~/setup-frontend.sh

